# Generated by Django 2.2.6 on 2019-10-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberCourse', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='IdDepartment',
        ),
        migrations.RemoveField(
            model_name='group',
            name='NumberCourse',
        ),
        migrations.AddField(
            model_name='timetable',
            name='IdDepartment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Department'),
        ),
        migrations.AddField(
            model_name='group',
            name='IdCourse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
    ]
