# Generated by Django 2.2.6 on 2019-10-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191010_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='IdDepartment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Department'),
        ),
    ]
