# Generated by Django 2.2.6 on 2019-10-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teacher_iddepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='NameFaculty',
            new_name='NameFaculty_ru',
        ),
    ]
