# Generated by Django 2.2.6 on 2019-10-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191020_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='NameDepartment',
            new_name='NameDepartment_ru',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='TypeWeek',
            new_name='TypeWeek_ru',
        ),
    ]
