# Generated by Django 2.2.6 on 2019-10-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191020_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayweek',
            old_name='NameDay',
            new_name='NameDay_ru',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='NameSubject',
            new_name='NameSubject_ru',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='Name_ru',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Patronymic',
            new_name='Patronymic_ru',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Surname',
            new_name='Surname_ru',
        ),
        migrations.RenameField(
            model_name='typesubject',
            old_name='nametypesubject',
            new_name='NameTypeSubject_ru',
        ),
    ]
